# Generated by Django 5.2.6 on 2025-09-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('3-5', '3-5 years'), ('6-8', '6-8 years'), ('9-12', '9-12 years'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sound_music',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sound_voice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark'), ('forest', 'Forest'), ('ocean', 'Ocean'), ('space', 'Space')], default='light', max_length=20),
        ),
    ]
