# Generated by Django 5.2.7 on 2025-10-10 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_assignment_assignmentresult_parentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='guardians', to=settings.AUTH_USER_MODEL),
        ),
    ]
