# Generated by Django 5.2.6 on 2025-10-10 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_parentprofile_children'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
